# Site settings
title: "Josh Orcullo"
#description: "A personal website showcasing my projects, blog posts, and professional journey."
#url: "https://jorcullo.github.io/jorcullo/" # Replace with your GitHub Pages URL
#baseurl: "" # Leave empty for user/organization pages or set to "/repository-name" for project pages

# Theme settings
remote_theme: "jekyll/minima@1e8a445"


# Author details
#author:
#  name: "Josh Orcullo"
#  email: "josh.ocullo@gmail.com"  # Update with your preferred contact email

# Social links (optional)
#social:
#  linkedin: "https://www.linkedin.com/in/josephorcullo"
#  facebook: "https://www.facebook.com/josh.orcullo"


